[package]
name = "backend"
version = "1.0.0"
authors = ["fgsoap <fgsoap@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.6"
ssh2 = "0.9"
log = "0.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.9"
futures = "0.3"
