[package]
name = "backend"
version = "1.0.0"
authors = ["fgsoap <fgsoap@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-cors = "0.4"
ssh2 = "0.8.0"
log = "0.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.7"
futures = "0.3"
