[workspace]

members = [
    "guessing_game",
    "variables",
    "branches",
    "loops",
    "template-web-ssh",
    "ownership",
    "first_word",
    "slice",
    "test_struct",
    "rectangles",
    "vue-web-ssh/backend",
    "test_emum"
]