[package]
name = "test_as"
version = "0.1.0"
authors = ["Scott Xu <jianx2@cisco.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
