[package]
name = "back_of_house"
version = "0.1.0"
authors = ["Scott Xu <jianx2@cisco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
